name: app_uninstaller
description:  Flutter plugin to uninstall android apps.
version: 0.4.1
homepage: https://github.com/CodersTurf/app_uninstaller

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.frendyapp.app_uninstaller
        pluginClass: AppUninstallerPlugin
      ios:
        pluginClass: AppUninstallerPlugin
